In [2]:
import torch

In [3]:
lista = [
    [1, 2, 3],
    [4, 5, 6]
]

In [4]:
tns = torch.Tensor(lista)
print(tns.dtype)
print(tns)

tns = torch.FloatTensor(lista)
print(tns.dtype)
print(tns)

tns = torch.DoubleTensor(lista)
print(tns.dtype)
print(tns)

tns = torch.LongTensor(lista)
print(tns.dtype)
print(tns)

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


In [5]:
import numpy as np

In [6]:
arr = np.random.rand(3,4)
tns = torch.from_numpy(arr)

print(arr)
print(tns)

[[0.74686591 0.28918333 0.68966976 0.55235497]
 [0.28335999 0.21651978 0.10576961 0.94031868]
 [0.6497119  0.37988011 0.65012432 0.76152449]]
tensor([[0.7469, 0.2892, 0.6897, 0.5524],
        [0.2834, 0.2165, 0.1058, 0.9403],
        [0.6497, 0.3799, 0.6501, 0.7615]], dtype=torch.float64)


In [7]:
tns0 = torch.ones(2,3)
print(tns0)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [8]:
tns1 = torch.zeros(2,3)
print(tns1)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [9]:
tnsr = torch.randn(3,3)
print(tnsr)

tensor([[-0.3558,  0.5965,  0.3879],
        [-0.0036,  0.8396,  0.7825],
        [-0.7336, -1.2041,  0.4156]])


In [10]:
torch.randn(3,3).data.numpy()

array([[ 0.924743  ,  1.8852303 , -0.06832208],
       [ 0.32348323, -0.45561182, -1.1800282 ],
       [ 0.25412473,  0.20067097, -0.10144923]], dtype=float32)

In [11]:
print(tnsr)
tnsr[0,2] = -10

print('')
print(tnsr)

print('')
print(tnsr[0:2])

print('')
print(tnsr[:,2])

tensor([[-0.3558,  0.5965,  0.3879],
        [-0.0036,  0.8396,  0.7825],
        [-0.7336, -1.2041,  0.4156]])

tensor([[-3.5582e-01,  5.9653e-01, -1.0000e+01],
        [-3.5642e-03,  8.3963e-01,  7.8254e-01],
        [-7.3362e-01, -1.2041e+00,  4.1564e-01]])

tensor([[-3.5582e-01,  5.9653e-01, -1.0000e+01],
        [-3.5642e-03,  8.3963e-01,  7.8254e-01]])

tensor([-10.0000,   0.7825,   0.4156])


In [19]:
tns = torch.randn(2,2,3)

print(tns)
print(tns.size())
print(tns.view(12))


tensor([[[-0.7568,  0.8469,  1.4069],
         [ 1.3941,  0.3057, -0.0502]],

        [[-1.3331, -0.9095,  1.0995],
         [ 0.1977,  0.3614, -0.7334]]])
torch.Size([2, 2, 3])
tensor([-0.7568,  0.8469,  1.4069,  1.3941,  0.3057, -0.0502, -1.3331, -0.9095,
         1.0995,  0.1977,  0.3614, -0.7334])


In [21]:
tns = torch.randn(10)

if torch.cuda.is_available():
    device = torch.device('cuda')
else:
    device = torch.device('cpu')
    
print(device)

tns = tns.to(device)
print(tns)

cuda
tensor([ 0.0910,  1.3540, -0.3180, -1.0293,  0.3448,  0.2787,  0.4285,  1.0569,
        -1.1754,  0.2354], device='cuda:0')
